name: Code check

on:
  push:
    branches: ['develop']

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Copy environment variables
        run: cp .env.example .env.local

      - run: SKIP_ENV_VALIDATION=1 pnpm lint

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Copy environment variables
        run: cp .env.example .env.local

      - run: pnpm check-format

  tsc:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Copy environment variables
        run: cp .env.example .env.local

      - name: Check types
        run: pnpm check-types
